
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOL CHAR CLASS COLON COMMA DOUBLE EQUALS FLOAT ID INT LCP LP NUMBER PRIVATE PROTECTED PUBLIC RCP RP SEMICOL VOIDstart : CLASS ID COLON access ID LCP empty RCPaccess : PRIVATE\n              | PUBLIC\n              | PROTECTEDempty : '
    
_lr_action_items = {'CLASS':([0,],[2,]),'$end':([1,12,],[0,-1,]),'ID':([2,5,6,7,8,],[3,9,-2,-3,-4,]),'COLON':([3,],[4,]),'PRIVATE':([4,],[6,]),'PUBLIC':([4,],[7,]),'PROTECTED':([4,],[8,]),'LCP':([9,],[10,]),'RCP':([10,11,],[-5,12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'access':([4,],[5,]),'empty':([10,],[11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> CLASS ID COLON access ID LCP empty RCP','start',8,'p_start','c6.py',40),
  ('access -> PRIVATE','access',1,'p_access','c6.py',44),
  ('access -> PUBLIC','access',1,'p_access','c6.py',45),
  ('access -> PROTECTED','access',1,'p_access','c6.py',46),
  ('empty -> <empty>','empty',0,'p_empty','c6.py',50),
]
